"""Interactive first-run wizard.

Runs in the plain terminal (before the TUI launches) using Rich prompts. Asks
for the default provider, how to store its API key (env var reference or the OS
keychain — never inlined), the default model, permission mode, and theme; then
writes ``~/.jarn/config.yaml`` and optionally validates the key with a tiny call.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import yaml
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

from jarn.config import paths
from jarn.config.defaults import (
    ALL_PROVIDERS,
    CLOUD_PROVIDERS,
    CUSTOM_OPENAI_PROFILE,
    DEFAULT_MODELS,
    EDITABLE_BASE_URL_PROFILES,
    PROVIDER_BASE_URLS,
    PROVIDER_ENV_VARS,
)
from jarn.config.secrets import store_keychain
from jarn.providers import strip_profile
from jarn.tui.logo import TAGLINE, WORDMARK

console = Console()

_CLOUD = CLOUD_PROVIDERS
_PROFILES = ALL_PROVIDERS

_CONFIG_HEADER = """\
# J.A.R.N. configuration — generated by `jarn setup`.
# API keys are referenced, never inlined:
#   ${ENV_VAR}                -> read from the environment
#   keychain:jarn/<provider>  -> read from the OS keychain
# Docs: https://github.com/chayapats/jarn/tree/main/docs
"""


def profile_needs_base_url(profile: str) -> bool:
    """True when setup should collect a custom ``base_url`` for ``profile``."""
    return profile in EDITABLE_BASE_URL_PROFILES


def normalize_openai_base_url(url: str) -> str:
    """Normalize an OpenAI-compatible endpoint URL (append ``/v1`` when bare)."""
    cleaned = url.strip().rstrip("/")
    if not cleaned:
        raise ValueError("base URL is required")
    parsed = urlparse(cleaned)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise ValueError(f"invalid base URL {url!r} (expected http(s)://host[:port][/v1])")
    if parsed.path in ("", "/"):
        return f"{cleaned}/v1"
    return cleaned


def normalize_base_url(profile: str, url: str) -> str:
    """Normalize a provider base URL (Ollama keeps host-only; others get ``/v1``)."""
    cleaned = url.strip().rstrip("/")
    if not cleaned:
        raise ValueError("base URL is required")
    parsed = urlparse(cleaned)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise ValueError(f"invalid base URL {url!r}")
    if profile == "ollama":
        return cleaned
    return normalize_openai_base_url(url)


def derive_routing_models(profile: str, main_model: str) -> dict[str, Any]:
    """Build routing entries aligned with the user's chosen main model.

    Custom / placeholder defaults keep subagent and summarizer on the same model
    so ``/compact`` and delegated tasks don't point at ``your-model``.
    """
    defaults = DEFAULT_MODELS.get(profile, DEFAULT_MODELS["openrouter"])
    sub = defaults["subagent"]
    summ = defaults["summarizer"]
    sub_id = strip_profile(sub, profile)
    if profile == CUSTOM_OPENAI_PROFILE or sub_id in ("your-model", ""):
        sub = summ = main_model
    return {
        "main": main_model,
        "subagent": sub,
        "summarizer": summ,
        "fallback": [],
    }


def confirm_overwrite(*, force: bool = False) -> bool:
    """Ask before replacing an existing global config. Returns True to proceed."""
    config_path = paths.global_config_path()
    if force or not config_path.is_file():
        return True
    if Confirm.ask(f"{config_path} exists. Overwrite?", default=False):
        return True
    console.print("[yellow]Keeping existing config.[/yellow]")
    return False


def run_wizard(*, force: bool = False) -> Path | None:
    """Run the wizard and write the global config. Returns the config path."""
    if not confirm_overwrite(force=force):
        return paths.global_config_path()

    config_path = paths.global_config_path()
    paths.global_home().mkdir(parents=True, exist_ok=True)

    console.print(Panel.fit(f"[b cyan]{WORDMARK}[/b cyan]\n[dim]{TAGLINE}[/dim]",
                            border_style="cyan"))
    console.print("Let's get you set up. This writes [b]~/.jarn/config.yaml[/b].\n")

    profile = Prompt.ask(
        "Default provider profile", choices=list(_PROFILES), default="openrouter"
    )

    api_key_ref = _configure_key(profile)
    base_url = _configure_base_url(profile) if profile_needs_base_url(profile) else None
    default_model = _prompt_model(profile)
    theme = Prompt.ask(
        "Theme", choices=["dark", "light", "high-contrast"], default="dark"
    )

    config = _build_config_dict(
        profile, api_key_ref, default_model, theme, base_url_override=base_url
    )
    config_path.write_text(_CONFIG_HEADER + yaml.safe_dump(config, sort_keys=False,
                                                           allow_unicode=True),
                           encoding="utf-8")
    console.print(f"\n[green]✔[/green] Wrote {config_path}")

    if profile in _CLOUD and Confirm.ask("Validate the API key now?", default=True):
        validate_config(profile, default_model, config)

    console.print("\n[b cyan]All set.[/b cyan] Launch with [b]jarn[/b].")
    return config_path


def _prompt_model(profile: str) -> str:
    from jarn.providers import qualify_model_ref

    default_full = DEFAULT_MODELS[profile]["main"]
    default_id = strip_profile(default_full, profile)
    if profile == CUSTOM_OPENAI_PROFILE and default_id == "your-model":
        default_id = "gpt-4o"
    if profile_needs_base_url(profile) or "/" not in default_full:
        raw = Prompt.ask(
            "Model id on your endpoint" if profile == CUSTOM_OPENAI_PROFILE
            else f"Model id for {profile}",
            default=default_id,
        )
        return qualify_model_ref(raw, profile)
    return Prompt.ask("Default model (main agent)", default=default_full)


def _configure_key(profile: str) -> str | None:
    if profile not in _CLOUD:
        console.print(f"[dim]{profile} is local — no API key needed.[/dim]")
        return None

    env_var = PROVIDER_ENV_VARS.get(profile, f"{profile.upper()}_API_KEY")
    console.print(f"\nHow should J.A.R.N. read your [b]{profile}[/b] API key?")
    method = Prompt.ask(
        "  storage", choices=["env", "keychain"], default="env"
    )
    if method == "env":
        console.print(f"  [dim]J.A.R.N. will read it from ${env_var}.[/dim]")
        return f"${{{env_var}}}"

    key = Prompt.ask("  paste API key", password=True)
    if key:
        store_keychain("jarn", profile, key)
        console.print(f"  [green]✔[/green] stored in OS keychain (jarn/{profile})")
        return f"keychain:jarn/{profile}"
    return f"${{{env_var}}}"


def _configure_base_url(profile: str) -> str:
    default = PROVIDER_BASE_URLS.get(profile, "http://localhost:8000/v1")
    while True:
        raw = Prompt.ask(
            f"API base URL for {profile}",
            default=default,
        )
        try:
            return normalize_base_url(profile, raw)
        except ValueError as exc:
            console.print(f"  [yellow]![/yellow] {exc}")


def _build_config_dict(
    profile: str,
    api_key_ref: str | None,
    default_model: str,
    theme: str,
    *,
    mode: str = "ask",
    base_url_override: str | None = None,
) -> dict[str, Any]:
    providers: dict[str, Any] = {}
    for name in _PROFILES:
        entry: dict[str, Any] = {"type": name}
        if name in _CLOUD:
            entry["api_key"] = (
                api_key_ref if name == profile
                else f"${{{PROVIDER_ENV_VARS.get(name, name.upper() + '_API_KEY')}}}"
            )
        if name in PROVIDER_BASE_URLS:
            if name == profile and base_url_override:
                entry["base_url"] = base_url_override
            else:
                entry["base_url"] = PROVIDER_BASE_URLS[name]
        providers[name] = entry

    return {
        "default_profile": profile,
        "default_model": default_model,
        "permission_mode": mode,
        "providers": providers,
        "routing": derive_routing_models(profile, default_model),
        "budget": {"per_session_usd": 5.0, "hard_stop": True, "warn_at_pct": 80},
        "context": {"auto_compact": True, "compact_at_pct": 85},
        "execution": {"local_sandbox": "auto"},
        "permissions": {"allow": [], "deny": []},
        "observability": {"langsmith": False, "telemetry": False, "log_level": "info"},
        "ui": {"theme": theme, "accent": "cyan"},
    }


def validate_config(profile: str, model: str, config: dict[str, Any]) -> bool:
    """Send a 1-token ping to confirm the key/model work. Returns success."""
    from jarn.config.loader import _build_config
    from jarn.providers import ModelFactory

    try:
        cfg = _build_config(config)
        factory = ModelFactory(cfg)
        chat = factory.build(model)
        resp = chat.invoke("ping")
        console.print(f"  [green]✔[/green] model responded ({len(str(resp.content))} chars)")
        return True
    except Exception as exc:  # noqa: BLE001
        console.print(f"  [yellow]![/yellow] validation failed: {exc}")
        console.print("  [dim]You can fix the key/model later in ~/.jarn/config.yaml.[/dim]")
        return False
