"""Interactive first-run wizard.

Runs in the plain terminal (before the TUI launches) using Rich prompts. Asks
for the default provider, how to store its API key (env var reference or the OS
keychain — never inlined), the default model, and theme; then writes
``~/.jarn/config.yaml`` and optionally validates the key with a tiny call.
"""

from __future__ import annotations

import contextlib
import json
import os
import signal
import subprocess
import sys
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor
from copy import deepcopy
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import yaml
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

from jarn.config import paths
from jarn.config.defaults import (
    ALL_PROVIDERS,
    CLOUD_PROVIDERS,
    CUSTOM_OPENAI_PROFILE,
    DEFAULT_MODELS,
    EDITABLE_BASE_URL_PROFILES,
    PROVIDER_BASE_URLS,
    PROVIDER_ENV_VARS,
)
from jarn.config.secrets import file_fallback_notice, store_secret
from jarn.onboarding.model_catalog import (
    load_setup_catalog,
    recommended_setup_model,
    selectable_setup_models,
    setup_catalog_status,
)
from jarn.onboarding.oauth import LoginResult, login_openrouter
from jarn.onboarding.outcome import (
    SetupCommandError,
    SetupFailureKind,
    return_or_raise_setup_failure,
)
from jarn.providers import qualify_model_ref, strip_profile
from jarn.tui import grammar, layout, palette
from jarn.tui.i18n import resolve_locale, t
from jarn.tui.logo import TAGLINE, WORDMARK

console = Console()

_CLOUD = CLOUD_PROVIDERS
_PROFILES = ALL_PROVIDERS


def _t(key: str, **kwargs: object) -> str:
    return t(key, resolve_locale("auto"), **kwargs)


def _setup_command() -> str:
    return layout.strong("jarn setup")


def _cancelled_notice() -> str:
    return (
        f"\n{layout.warn(_t('onboarding.cancelled'))} "
        f"{_t('onboarding.resume_with', command=_setup_command())}"
    )


def _detect_env_key() -> tuple[str, str] | None:
    """Probe known provider env vars and return (provider, env_var) for the first hit.

    Checks providers in priority order: anthropic, openai, openrouter, then the rest.
    Returns ``None`` when no key is found in the environment.
    """
    priority = ["anthropic", "openai", "openrouter"]
    rest = [p for p in ALL_PROVIDERS if p not in priority]
    for provider in priority + rest:
        env_var = PROVIDER_ENV_VARS.get(provider)
        if env_var and os.environ.get(env_var):
            return provider, env_var
    return None


def _recommended_provider(
    env_hit: tuple[str, str] | None,
    *,
    chatgpt_ready: bool = False,
) -> str:
    """Return the provider that should be marked '★ recommended'.

    Priority: verified ChatGPT session > detected provider key > ChatGPT.
    """
    if chatgpt_ready:
        return "codex_subscription"
    if env_hit is not None:
        return env_hit[0]
    if os.environ.get("ANTHROPIC_API_KEY"):
        return "anthropic"
    return "codex_subscription"


def _chatgpt_session_ready(*, timeout_seconds: float = 5.0) -> bool:
    """Best-effort existing-account detection used only by real setup entrypoints."""

    from jarn.auth import CodexAuthService

    return CodexAuthService(timeout_seconds=timeout_seconds).status(refresh=False).ready


def _detect_local_providers() -> tuple[str, ...]:
    """Return default local endpoints that currently report at least one model."""

    names = ("ollama", "lmstudio")

    def reachable(name: str) -> bool:
        snapshot = load_setup_catalog(
            name,
            base_url=PROVIDER_BASE_URLS.get(name),
            on_wait=lambda message: console.print(layout.muted(message)),
        )
        return bool(selectable_setup_models(snapshot))

    with ThreadPoolExecutor(max_workers=len(names)) as pool:
        checks = dict(zip(names, pool.map(reachable, names), strict=True))
    return tuple(name for name in names if checks[name])


_CONFIG_HEADER = """\
# J.A.R.N. configuration — generated by `jarn setup`.
# API keys are referenced, never inlined:
#   ${ENV_VAR}                -> read from the environment
#   keychain:jarn/<provider>  -> read from the OS keychain
#   file:jarn/<provider>      -> read from ~/.jarn/secrets/ (keychain fallback)
# Docs: https://github.com/chayapats/jarn/tree/main/docs
"""


def profile_needs_base_url(profile: str) -> bool:
    """True when setup should collect a custom ``base_url`` for ``profile``."""
    return profile in EDITABLE_BASE_URL_PROFILES


def normalize_openai_base_url(url: str) -> str:
    """Normalize an OpenAI-compatible endpoint URL (append ``/v1`` when bare)."""
    cleaned = url.strip().rstrip("/")
    if not cleaned:
        raise ValueError("base URL is required")
    parsed = urlparse(cleaned)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise ValueError(f"invalid base URL {url!r} (expected http(s)://host[:port][/v1])")
    if parsed.path in ("", "/"):
        return f"{cleaned}/v1"
    return cleaned


def normalize_base_url(profile: str, url: str) -> str:
    """Normalize a provider base URL (Ollama keeps host-only; others get ``/v1``)."""
    cleaned = url.strip().rstrip("/")
    if not cleaned:
        raise ValueError("base URL is required")
    parsed = urlparse(cleaned)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise ValueError(f"invalid base URL {url!r}")
    if profile == "ollama":
        return cleaned
    return normalize_openai_base_url(url)


def derive_routing_models(profile: str, main_model: str) -> dict[str, Any]:
    """Build routing entries aligned with the user's chosen main model.

    Custom / placeholder defaults keep subagent and summarizer on the same model
    so ``/compact`` and delegated tasks don't point at ``your-model``.
    """
    defaults = DEFAULT_MODELS.get(profile, DEFAULT_MODELS["openrouter"])
    sub = defaults["subagent"]
    summ = defaults["summarizer"]
    sub_id = strip_profile(sub, profile)
    if profile in (CUSTOM_OPENAI_PROFILE, "codex_subscription") or sub_id in ("your-model", ""):
        sub = summ = main_model
    return {
        "main": main_model,
        "subagent": sub,
        "summarizer": summ,
        "fallback": [],
    }


def confirm_overwrite(*, force: bool = False) -> bool:
    """Ask before updating an existing global config. Returns True to proceed."""
    config_path = paths.global_config_path()
    if force or not config_path.is_file():
        return True
    if Confirm.ask(
        _t("onboarding.overwrite", path=str(config_path)),
        default=False,
    ):
        return True
    console.print(layout.warn(_t("onboarding.overwrite.keep")))
    return False


class _PlainBack(Exception):
    pass


class _PlainCancel(Exception):
    pass


def _plain_menu(prompt: str, choices: list[str], *, default: str) -> str:
    value = Prompt.ask(
        prompt,
        choices=[*choices, "back", "cancel"],
        default=default,
    )
    if value == "back":
        raise _PlainBack
    if value == "cancel":
        raise _PlainCancel
    return value


def _plain_text(prompt: str, *, default: str = "", password: bool = False) -> str:
    value = Prompt.ask(
        f"{prompt} {layout.muted(_t('onboarding.nav.back_cancel'))}",
        default=default,
        password=password,
    )
    if value.strip() == "/back":
        raise _PlainBack
    if value.strip() == "/cancel":
        raise _PlainCancel
    return value


def _plain_previous(stage: str, answers: dict[str, str]) -> str:
    provider = answers.get("provider", "")
    if stage == "provider":
        return "cancel"
    if stage == "storage":
        return "provider"
    if stage == "key":
        return "storage"
    if stage == "base_url":
        return "storage" if provider in CLOUD_PROVIDERS else "provider"
    if stage == "model":
        if profile_needs_base_url(provider):
            return "base_url"
        return "storage" if provider in CLOUD_PROVIDERS else "provider"
    if stage == "reasoning":
        return "model"
    if stage == "subagent_model":
        return "reasoning"
    if stage == "summarizer_model":
        return "subagent_model"
    if stage == "fallback_models":
        return "summarizer_model"
    if stage == "budget":
        return "fallback_models"
    if stage == "budget_warn":
        return "budget"
    if stage == "budget_stop":
        return "budget_warn"
    if stage == "permissions":
        return "budget_stop"
    if stage == "theme":
        if answers.get("_provider_group") == "advanced":
            return "permissions"
        if provider == "codex_subscription":
            return "provider"
        if answers.get("_provider_group") == "advanced" or provider in ("ollama", "lmstudio"):
            return "model"
        return "storage" if provider in CLOUD_PROVIDERS else "provider"
    if stage == "confirm":
        return "theme"
    return "provider"


def _advanced_model_ref(value: str, provider: str) -> str:
    """Accept an explicit profile ref or qualify a model under the selected provider."""

    from jarn.providers import qualify_model_ref

    cleaned = value.strip()
    if any(cleaned.startswith(f"{profile}/") for profile in ALL_PROVIDERS):
        return cleaned
    return qualify_model_ref(cleaned, provider)


def _advanced_fallback_refs(value: str, provider: str) -> str:
    return ",".join(
        _advanced_model_ref(item, provider) for item in value.split(",") if item.strip()
    )


def _plain_next_after_provider(provider: str, group: str) -> str:
    if provider == "codex_subscription":
        return "theme"
    if provider in CLOUD_PROVIDERS:
        return "storage"
    if profile_needs_base_url(provider):
        return "base_url"
    return "model" if group == "advanced" else "theme"


def _catalog_for_answers(
    answers: dict[str, str],
    pending_credentials: Any,
):
    """Fetch setup's current provider through the shared catalog abstraction."""

    provider = answers["provider"]
    credential = pending_credentials.get(provider) or answers.get("key_ref")
    return load_setup_catalog(
        provider,
        credential=credential,
        base_url=answers.get("base_url") or PROVIDER_BASE_URLS.get(provider),
        include_hidden=answers.get("_provider_group") == "advanced",
        on_wait=lambda message: console.print(layout.muted(message)),
    )


def _remember_catalog_status(
    answers: dict[str, str],
    *,
    provenance: str,
    verified: bool,
) -> None:
    answers["_model_catalog_provenance"] = provenance
    answers["_model_catalog_verified"] = "true" if verified else "false"


def _apply_standard_catalog_model(
    answers: dict[str, str],
    pending_credentials: Any,
) -> None:
    """Choose a verified live/default model, or label bootstrap data honestly."""

    provider = answers["provider"]
    snapshot = _catalog_for_answers(answers, pending_credentials)
    selected = recommended_setup_model(snapshot)
    if selected is not None:
        answers["model"] = selected.ref
        _remember_catalog_status(
            answers,
            provenance=snapshot.provenance_label,
            verified=True,
        )
        return

    # Standard setup still needs an exact candidate for the explicitly
    # consented readiness request in the completion gate.  This shipped value
    # is a bootstrap input only; the status shown at confirmation makes clear
    # that it has not been reported by the configured account/endpoint.
    answers["model"] = DEFAULT_MODELS.get(provider, DEFAULT_MODELS["openrouter"])["main"]
    _remember_catalog_status(
        answers,
        provenance=(
            f"{setup_catalog_status(snapshot)}; shipped bootstrap candidate, "
            "not proof of availability"
        ),
        verified=False,
    )


def run_wizard(
    *,
    force: bool = False,
    propagate_errors: bool = False,
    _resume: bool = False,
    _pending_credentials: Any | None = None,
) -> Path | None:
    """Run resumable plain setup and commit only after every gate succeeds."""
    from jarn.install_state import InstallStateError
    from jarn.onboarding.credentials import PendingCredentials
    from jarn.onboarding.flow import (
        SetupFlowError,
        finalize_setup,
        mark_setup_incomplete,
        set_setup_progress,
    )
    from jarn.onboarding.state import load_setup_state, save_setup_state

    try:
        proceed = confirm_overwrite(force=force)
    except (KeyboardInterrupt, EOFError):
        mark_setup_incomplete()
        console.print(_cancelled_notice())
        return return_or_raise_setup_failure(
            SetupCommandError("The setup prompt was cancelled.", kind=SetupFailureKind.CANCELLED),
            propagate_errors=propagate_errors,
        )
    if not proceed:
        mark_setup_incomplete()
        return return_or_raise_setup_failure(
            SetupCommandError("The setup overwrite was declined.", kind=SetupFailureKind.CANCELLED),
            propagate_errors=propagate_errors,
        )

    paths.ensure_global_home()
    # Best-effort by contract, so it swallows a create failure. The wizard is
    # about to write config.yaml and must fail BEFORE the first prompt, not after
    # the operator has answered all of them.
    paths.global_home().mkdir(parents=True, exist_ok=True)

    console.print(
        Panel.fit(
            f"{layout.accent(WORDMARK, bold=True)}\n{layout.muted(TAGLINE)}",
            border_style=palette.ACCENT,
        )
    )
    console.print(_t("onboarding.intro", path=layout.strong("~/.jarn/config.yaml")) + "\n")

    try:
        set_setup_progress("in_progress")
    except SetupFlowError as exc:
        console.print(f"{layout.err(_t('onboarding.incomplete.install'))} {exc}")
        return return_or_raise_setup_failure(exc, propagate_errors=propagate_errors)

    # -- probes and resumable non-secret progress -------------------------
    env_hit = _detect_env_key()
    chatgpt_ready = _chatgpt_session_ready()
    local_providers = _detect_local_providers()
    recommended = _recommended_provider(env_hit, chatgpt_ready=chatgpt_ready)
    pending_credentials = _pending_credentials or PendingCredentials()
    saved = load_setup_state()
    answers: dict[str, str] = {}
    stage = "provider"
    try:
        should_resume = saved is not None and (
            _resume
            or Confirm.ask(
                _t("onboarding.resume", stage=saved.stage, updated_at=saved.updated_at),
                default=True,
            )
        )
    except (KeyboardInterrupt, EOFError):
        mark_setup_incomplete()
        console.print(_cancelled_notice())
        return return_or_raise_setup_failure(
            SetupCommandError("Setup resume was cancelled.", kind=SetupFailureKind.CANCELLED),
            propagate_errors=propagate_errors,
        )
    if saved is not None and should_resume:
        answers.update(saved.answers)
        stage = saved.stage
        if answers.get("_credential_pending") and not pending_credentials.contains(
            answers.get("provider", "")
        ):
            answers.pop("_credential_pending", None)
            stage = "key"
        console.print(
            f"{layout.ok(grammar.GLYPH_OK)} {_t('onboarding.resuming', stage=layout.strong(stage))}"
        )
    else:
        save_setup_state("provider", answers)

    known_stages = {
        "provider",
        "storage",
        "key",
        "base_url",
        "model",
        "reasoning",
        "subagent_model",
        "summarizer_model",
        "fallback_models",
        "budget",
        "budget_warn",
        "budget_stop",
        "permissions",
        "theme",
        "confirm",
    }
    if stage not in known_stages:
        stage = "provider"

    try:
        while True:
            provider = answers.get("provider", "")
            group = answers.get("_provider_group", "")
            if stage == "provider":
                default_choice = {
                    "codex_subscription": "chatgpt",
                    "anthropic": "anthropic",
                    "ollama": "local",
                    "lmstudio": "local",
                }.get(recommended, "cloud")
                local_note = (
                    _t("onboarding.connect.local.found", names=", ".join(local_providers))
                    if local_providers
                    else ""
                )
                console.print("\n" + _t("onboarding.connect.heading"))
                console.print(f"  chatgpt   — {_t('onboarding.connect.chatgpt')}")
                console.print(f"  anthropic — {_t('onboarding.connect.anthropic')}")
                console.print(f"  cloud     — {_t('onboarding.connect.cloud')}")
                console.print(f"  local     — {_t('onboarding.connect.local')}{local_note}")
                console.print(f"  {layout.muted(_t('onboarding.connect.advanced.hint'))}")
                connection = _plain_menu(
                    _t("onboarding.connect.prompt"),
                    ["chatgpt", "anthropic", "cloud", "local", "advanced"],
                    default=default_choice,
                )
                if connection == "chatgpt":
                    selected, group = "codex_subscription", "standard"
                elif connection == "anthropic":
                    selected, group = "anthropic", "standard"
                elif connection == "cloud":
                    cloud_profiles = [
                        p
                        for p in CLOUD_PROVIDERS
                        if p not in ("anthropic", CUSTOM_OPENAI_PROFILE, "codex_subscription")
                    ]
                    try:
                        selected = _plain_menu(
                            _t("onboarding.cloud.prompt"),
                            cloud_profiles,
                            default=(
                                recommended if recommended in cloud_profiles else "openrouter"
                            ),
                        )
                    except _PlainBack:
                        save_setup_state("provider", answers)
                        continue
                    group = "cloud"
                elif connection == "local":
                    local_choices = [
                        *local_providers,
                        *(p for p in ("ollama", "lmstudio") if p not in local_providers),
                    ]
                    try:
                        selected = _plain_menu(
                            _t("onboarding.local.prompt"), local_choices, default=local_choices[0]
                        )
                    except _PlainBack:
                        save_setup_state("provider", answers)
                        continue
                    group = "local"
                else:
                    advanced_profiles = [
                        profile for profile in _PROFILES if profile != "codex_subscription"
                    ]
                    console.print(
                        _t("onboarding.advanced.list", names=", ".join(advanced_profiles))
                    )
                    try:
                        selected = _plain_menu(
                            _t("onboarding.provider.prompt"),
                            advanced_profiles,
                            default=(recommended if recommended in _PROFILES else "openrouter"),
                        )
                    except _PlainBack:
                        save_setup_state("provider", answers)
                        continue
                    group = "advanced"
                if selected != provider:
                    if provider:
                        pending_credentials.discard(provider)
                    for key in ("storage", "key_ref", "base_url", "model", "reasoning_effort"):
                        answers.pop(key, None)
                    answers.pop("_model_catalog_provenance", None)
                    answers.pop("_model_catalog_verified", None)
                    answers.pop("_credential_pending", None)
                answers["provider"] = selected
                answers["_provider_group"] = group
                provider = selected
                stage = _plain_next_after_provider(provider, group)
                save_setup_state(stage, answers)
                continue

            if stage == "storage":
                env_var = PROVIDER_ENV_VARS.get(provider, f"{provider.upper()}_API_KEY")
                if env_hit is not None and env_hit[0] == provider:
                    console.print(
                        f"{layout.ok(grammar.GLYPH_OK)} "
                        f"{_t('onboarding.storage.env.using', env_var=layout.strong('$' + env_var))}"
                    )
                    answers["storage"] = "env"
                    pending_credentials.discard(provider)
                    answers.pop("_credential_pending", None)
                    answers["key_ref"] = f"${{{env_var}}}"
                    stage = (
                        "base_url"
                        if profile_needs_base_url(provider)
                        else ("model" if group == "advanced" else "theme")
                    )
                    if stage == "theme":
                        _apply_standard_catalog_model(answers, pending_credentials)
                    save_setup_state(stage, answers)
                    continue
                methods = ["env", "keychain"]
                method = _plain_menu(
                    _t("onboarding.storage.prompt", provider=provider),
                    methods,
                    default="keychain",
                )
                answers["storage"] = method
                if method == "env" and os.environ.get(env_var):
                    pending_credentials.discard(provider)
                    answers.pop("_credential_pending", None)
                    answers["key_ref"] = f"${{{env_var}}}"
                    stage = (
                        "base_url"
                        if profile_needs_base_url(provider)
                        else ("model" if group == "advanced" else "theme")
                    )
                    if stage == "theme":
                        _apply_standard_catalog_model(answers, pending_credentials)
                else:
                    if method == "env":
                        console.print(
                            f"{layout.warn(_t('onboarding.storage.env.unset', env_var='$' + env_var))} "
                            f"{_t('onboarding.storage.env.paste_now')}"
                        )
                    stage = "key"
                save_setup_state(stage, answers)
                continue

            if stage == "key":
                value = _plain_text(
                    _t("onboarding.key.paste", provider=provider), password=True
                ).strip()
                if not value:
                    console.print(layout.warn(_t("onboarding.key.required")))
                    continue
                pending_credentials.set(provider, value)
                answers["storage"] = "keychain"
                answers.pop("key_ref", None)
                answers["_credential_pending"] = "memory"
                stage = (
                    "base_url"
                    if profile_needs_base_url(provider)
                    else ("model" if group == "advanced" else "theme")
                )
                if stage == "theme":
                    _apply_standard_catalog_model(answers, pending_credentials)
                save_setup_state(stage, answers)
                continue

            if stage == "base_url":
                default_url = answers.get("base_url") or PROVIDER_BASE_URLS.get(
                    provider, "http://localhost:8000/v1"
                )
                try:
                    answers["base_url"] = normalize_base_url(
                        provider,
                        _plain_text(
                            _t("onboarding.base_url.prompt", provider=provider),
                            default=default_url,
                        ),
                    )
                except ValueError as exc:
                    console.print(layout.warn(str(exc)))
                    continue
                stage = (
                    "model"
                    if group == "advanced" or provider in ("ollama", "lmstudio")
                    else "theme"
                )
                if stage == "theme":
                    _apply_standard_catalog_model(answers, pending_credentials)
                save_setup_state(stage, answers)
                continue

            if stage == "model":
                default_full = (
                    answers.get("model")
                    or DEFAULT_MODELS.get(provider, DEFAULT_MODELS["openrouter"])["main"]
                )
                snapshot = _catalog_for_answers(answers, pending_credentials)
                discovered = selectable_setup_models(snapshot)
                if group != "advanced" and provider in ("ollama", "lmstudio"):
                    local_entry = recommended_setup_model(snapshot)
                    if local_entry is not None:
                        answers["model"] = local_entry.ref
                        _remember_catalog_status(
                            answers,
                            provenance=snapshot.provenance_label,
                            verified=True,
                        )
                        console.print(
                            f"{layout.ok(grammar.GLYPH_OK)} "
                            f"{_t('onboarding.model.using_local', model=layout.strong(answers['model']))}"
                        )
                        stage = "reasoning" if group == "advanced" else "theme"
                        save_setup_state(stage, answers)
                        continue
                    console.print(
                        f"{layout.warn(setup_catalog_status(snapshot) + '.')} "
                        f"{_t('onboarding.model.start_or_manual')}"
                    )

                if group == "advanced" and discovered:
                    ids = [entry.model_id for entry in discovered]
                    console.print(
                        f"{layout.ok(grammar.GLYPH_OK)} {snapshot.provenance_label}. "
                        f"{_t('onboarding.model.choose_reported')}"
                    )
                    picked = _plain_menu(
                        _t("onboarding.model.prompt", provider=provider),
                        [*ids, "manual"],
                        default=(
                            strip_profile(default_full, provider)
                            if strip_profile(default_full, provider) in ids
                            else ids[0]
                        ),
                    )
                    if picked != "manual":
                        answers["model"] = qualify_model_ref(picked, provider)
                        _remember_catalog_status(
                            answers,
                            provenance=snapshot.provenance_label,
                            verified=True,
                        )
                        stage = "reasoning"
                        save_setup_state(stage, answers)
                        continue
                elif group == "advanced":
                    console.print(
                        f"{layout.warn(setup_catalog_status(snapshot) + '.')} "
                        f"{_t('onboarding.model.manual_gate')}"
                    )

                default_id = strip_profile(default_full, provider)
                raw_model = _plain_text(
                    _t("onboarding.model.id", provider=provider), default=default_id
                )
                answers["model"] = qualify_model_ref(raw_model, provider)
                _remember_catalog_status(
                    answers,
                    provenance=(
                        "Manual model entry; availability unverified until the final readiness gate"
                    ),
                    verified=False,
                )
                stage = "reasoning" if group == "advanced" else "theme"
                save_setup_state(stage, answers)
                continue

            if stage == "reasoning":
                effort = _plain_menu(
                    _t("onboarding.reasoning"),
                    ["default", "low", "medium", "high", "xhigh"],
                    default=answers.get("reasoning_effort", "default"),
                )
                if effort == "default":
                    answers.pop("reasoning_effort", None)
                else:
                    answers["reasoning_effort"] = effort
                stage = "subagent_model"
                save_setup_state(stage, answers)
                continue

            if stage == "subagent_model":
                default_route = answers.get("routing_subagent") or answers["model"]
                raw = _plain_text(
                    _t("onboarding.subagent"),
                    default=default_route,
                )
                answers["routing_subagent"] = _advanced_model_ref(raw, provider)
                stage = "summarizer_model"
                save_setup_state(stage, answers)
                continue

            if stage == "summarizer_model":
                default_route = (
                    answers.get("routing_summarizer")
                    or answers.get("routing_subagent")
                    or answers["model"]
                )
                raw = _plain_text(
                    _t("onboarding.summarizer"),
                    default=default_route,
                )
                answers["routing_summarizer"] = _advanced_model_ref(raw, provider)
                stage = "fallback_models"
                save_setup_state(stage, answers)
                continue

            if stage == "fallback_models":
                raw = _plain_text(
                    _t("onboarding.fallback"),
                    default=answers.get("routing_fallback", ""),
                )
                answers["routing_fallback"] = _advanced_fallback_refs(raw, provider)
                stage = "budget"
                save_setup_state(stage, answers)
                continue

            if stage == "budget":
                raw = _plain_text(
                    _t("onboarding.budget"),
                    default=answers.get("budget_per_session_usd", "5.00"),
                )
                try:
                    budget_value = float(raw)
                    if not 0 <= budget_value < float("inf"):
                        raise ValueError
                except ValueError:
                    console.print(layout.warn(_t("onboarding.budget.invalid")))
                    continue
                answers["budget_per_session_usd"] = raw
                stage = "budget_warn"
                save_setup_state(stage, answers)
                continue

            if stage == "budget_warn":
                raw = _plain_text(
                    _t("onboarding.budget.warn"),
                    default=answers.get("budget_warn_at_pct", "80"),
                )
                try:
                    warn_value = int(raw)
                    if not 0 <= warn_value <= 100:
                        raise ValueError
                except ValueError:
                    console.print(layout.warn(_t("onboarding.budget.warn.invalid")))
                    continue
                answers["budget_warn_at_pct"] = raw
                stage = "budget_stop"
                save_setup_state(stage, answers)
                continue

            if stage == "budget_stop":
                choice = _plain_menu(
                    _t("onboarding.budget.stop"),
                    ["yes", "no"],
                    default="yes" if answers.get("budget_hard_stop", "true") == "true" else "no",
                )
                answers["budget_hard_stop"] = "true" if choice == "yes" else "false"
                stage = "permissions"
                save_setup_state(stage, answers)
                continue

            if stage == "permissions":
                console.print(f"  review — {_t('onboarding.perm.review')}")
                console.print(f"  ask    — {_t('onboarding.perm.ask')}")
                console.print(f"  edit   — {_t('onboarding.perm.edit')}")
                console.print(f"  full   — {_t('onboarding.perm.full')}")
                reverse = {"plan": "review", "ask": "ask", "auto-edit": "edit", "yolo": "full"}
                selected = _plain_menu(
                    _t("onboarding.perm.prompt"),
                    ["review", "ask", "edit", "full"],
                    default=reverse.get(answers.get("permission_mode", "ask"), "ask"),
                )
                answers["permission_mode"] = {
                    "review": "plan",
                    "ask": "ask",
                    "edit": "auto-edit",
                    "full": "yolo",
                }[selected]
                stage = "theme"
                save_setup_state(stage, answers)
                continue

            if stage == "theme":
                answers["theme"] = _plain_menu(
                    _t("onboarding.theme"),
                    ["dark", "light", "high-contrast"],
                    default=answers.get("theme", "dark"),
                )
                stage = "confirm"
                save_setup_state(stage, answers)
                continue

            console.print("\n" + _t("onboarding.confirm.ready"))
            provider_label = "ChatGPT" if provider == "codex_subscription" else provider
            console.print(f"  {layout.field(_t('onboarding.field.provider'), provider_label)}")
            console.print(
                f"  {layout.field(_t('onboarding.field.model'), answers.get('model', _t('onboarding.model.account_default')) or '')}"
            )
            if answers.get("_model_catalog_provenance"):
                status = (
                    _t("onboarding.catalog.verified")
                    if answers.get("_model_catalog_verified") == "true"
                    else _t("onboarding.catalog.unverified")
                )
                console.print(
                    f"  {layout.field(_t('onboarding.field.catalog'), status)} — "
                    f"{answers['_model_catalog_provenance']}"
                )
            console.print(
                f"  {layout.field(_t('onboarding.field.theme'), answers.get('theme', 'dark'))}"
            )
            if group == "advanced":
                console.print(
                    f"  {layout.field(_t('onboarding.field.subagent'), answers.get('routing_subagent') or '')}"
                )
                console.print(
                    f"  {layout.field(_t('onboarding.field.summarizer'), answers.get('routing_summarizer') or '')}"
                )
                console.print(
                    f"  {layout.field(_t('onboarding.field.fallbacks'), answers.get('routing_fallback') or _t('onboarding.none'))}"
                )
                console.print(
                    f"  {layout.field(_t('onboarding.field.budget'), _t('onboarding.budget.summary', amount='$' + str(answers.get('budget_per_session_usd', '5.00')), pct=answers.get('budget_warn_at_pct', '80'), hard=answers.get('budget_hard_stop', 'true')))}"
                )
                from jarn.permissions.labels import permission_mode_name

                console.print(
                    f"  {layout.field(_t('onboarding.field.permissions'), permission_mode_name(answers.get('permission_mode', 'ask')))}"
                )
            choice = _plain_menu(_t("onboarding.confirm.finish"), ["save"], default="save")
            if choice == "save":
                return finalize_setup(
                    answers,
                    console=console,
                    pending_credentials=pending_credentials,
                )
    except _PlainBack:
        previous = _plain_previous(stage, answers)
        if previous == "cancel":
            mark_setup_incomplete()
            console.print(_cancelled_notice())
            return return_or_raise_setup_failure(
                SetupCommandError(
                    "Back was selected on the first setup step.",
                    kind=SetupFailureKind.CANCELLED,
                ),
                propagate_errors=propagate_errors,
            )
        save_setup_state(previous, answers)
        # Continue in a new invocation-safe loop by recursively resuming the
        # just-persisted boundary; Prompt state itself contains no secret.
        return run_wizard(
            force=True,
            propagate_errors=propagate_errors,
            _resume=True,
            _pending_credentials=pending_credentials,
        )
    except (_PlainCancel, KeyboardInterrupt, EOFError):
        save_setup_state(stage, answers)
        mark_setup_incomplete()
        console.print(_cancelled_notice())
        return return_or_raise_setup_failure(
            SetupCommandError("Setup was cancelled by the user.", kind=SetupFailureKind.CANCELLED),
            propagate_errors=propagate_errors,
        )
    except (SetupFlowError, InstallStateError, OSError) as exc:
        save_setup_state(stage, answers)
        mark_setup_incomplete()
        console.print(f"\n{layout.err(_t('onboarding.incomplete.at', stage=stage))} {exc}")
        console.print(_t("onboarding.retry", command=_setup_command()))
        failure: SetupCommandError
        if isinstance(exc, SetupCommandError):
            failure = exc
        elif isinstance(exc, InstallStateError):
            failure = SetupCommandError(str(exc), kind=SetupFailureKind.VERIFICATION)
        else:
            failure = SetupCommandError(str(exc), kind=SetupFailureKind.CONFIG)
        return return_or_raise_setup_failure(failure, propagate_errors=propagate_errors)


def _prompt_model(profile: str) -> str:
    from jarn.providers import qualify_model_ref

    default_full = DEFAULT_MODELS[profile]["main"]
    default_id = strip_profile(default_full, profile)
    if profile == CUSTOM_OPENAI_PROFILE and default_id == "your-model":
        default_id = "gpt-4o"
    if profile_needs_base_url(profile) or "/" not in default_full:
        raw = Prompt.ask(
            _t("onboarding.model.id.endpoint")
            if profile == CUSTOM_OPENAI_PROFILE
            else _t("onboarding.model.id", provider=profile),
            default=default_id,
        )
        return qualify_model_ref(raw, profile)
    return Prompt.ask(_t("onboarding.model.main"), default=default_full)


def _configure_key(
    profile: str,
    *,
    env_hit: tuple[str, str] | None = None,
) -> str | None:
    """Determine the API key reference for *profile*.

    When *env_hit* is provided and matches *profile* (i.e. the user confirmed
    using the detected env key), return the ``${ENV_VAR}`` reference immediately
    without prompting — keeping the key out of the config verbatim.
    """
    if profile == "codex_subscription":
        console.print(layout.muted(_t("onboarding.key.codex")))
        return None

    if profile not in _CLOUD:
        console.print(layout.muted(_t("onboarding.key.local", provider=profile)))
        return None

    env_var = PROVIDER_ENV_VARS.get(profile, f"{profile.upper()}_API_KEY")

    # If the detected env key belongs to this provider, use it as a reference.
    if env_hit is not None and env_hit[0] == profile:
        console.print(
            "  " + layout.muted(_t("onboarding.key.read_from", env_var=f"${{{env_var}}}"))
        )
        return f"${{{env_var}}}"

    console.print("\n" + _t("onboarding.storage.prompt_your", provider=layout.strong(profile)))

    if profile == "openrouter":
        choices = ["oauth", "env", "keychain"]
        default_storage = "oauth"
        console.print(f"  oauth      — {_t('onboarding.storage.oauth')}")
        console.print(f"  env        — {_t('onboarding.storage.env.read', env_var='$' + env_var)}")
        console.print(f"  keychain   — {_t('onboarding.storage.keychain')}")
    else:
        choices = ["env", "keychain"]
        default_storage = "env"

    method = Prompt.ask(
        "  " + _t("onboarding.storage.method"), choices=choices, default=default_storage
    )

    if method == "oauth":
        console.print("  " + _t("onboarding.oauth.opening"))
        try:
            result: LoginResult = login_openrouter()
            console.print(
                f"  {layout.ok(grammar.GLYPH_OK)} "
                f"{_t('onboarding.oauth.logged_in', reference=result.reference)}"
            )
            return result.reference
        except Exception as exc:  # noqa: BLE001
            from jarn.config.secrets import redact_secrets

            console.print(
                f"  {layout.warn(grammar.GLYPH_WARN)} "
                f"{_t('onboarding.oauth.failed', error=redact_secrets(str(exc)))}"
            )
            # Fall through to keychain paste.
            method = "keychain"

    if method == "env":
        console.print("  " + layout.muted(_t("onboarding.key.read_it", env_var=f"${env_var}")))
        return f"${{{env_var}}}"

    key = Prompt.ask("  " + _t("onboarding.key.paste_prompt"), password=True)
    if key:
        stored = store_secret("jarn", profile, key)
        notice = file_fallback_notice(stored, provider=profile, env_var=env_var)
        if notice:
            console.print(layout.warn(notice))
        else:
            console.print(
                f"  {layout.ok(grammar.GLYPH_OK)} {_t('onboarding.key.stored', provider=profile)}"
            )
        return stored.reference
    return f"${{{env_var}}}"


def _configure_base_url(profile: str) -> str:
    default = PROVIDER_BASE_URLS.get(profile, "http://localhost:8000/v1")
    while True:
        raw = Prompt.ask(
            _t("onboarding.base_url.prompt", provider=profile),
            default=default,
        )
        try:
            return normalize_base_url(profile, raw)
        except ValueError as exc:
            console.print(f"  {layout.warn(grammar.GLYPH_WARN)} {exc}")


def _build_config_dict(
    profile: str,
    api_key_ref: str | None,
    default_model: str,
    theme: str,
    *,
    mode: str = "ask",
    base_url_override: str | None = None,
    reasoning_effort: str | None = None,
) -> dict[str, Any]:
    providers: dict[str, Any] = {}
    for name in _PROFILES:
        entry: dict[str, Any] = {"type": name}
        if name in _CLOUD:
            entry["api_key"] = (
                api_key_ref
                if name == profile
                else f"${{{PROVIDER_ENV_VARS.get(name, name.upper() + '_API_KEY')}}}"
            )
        if name in PROVIDER_BASE_URLS:
            if name == profile and base_url_override:
                entry["base_url"] = base_url_override
            else:
                entry["base_url"] = PROVIDER_BASE_URLS[name]
        if name == profile == "codex_subscription" and reasoning_effort:
            entry["reasoning_effort"] = reasoning_effort
        providers[name] = entry

    return {
        "default_profile": profile,
        "default_model": default_model,
        "permission_mode": mode,
        "providers": providers,
        "routing": derive_routing_models(profile, default_model),
        "budget": {"per_session_usd": 5.0, "hard_stop": True, "warn_at_pct": 80},
        "context": {"auto_compact": True, "compact_at_pct": 85},
        "execution": {"local_sandbox": "auto"},
        "permissions": {"allow": [], "deny": []},
        "observability": {"langsmith": False, "telemetry": False, "log_level": "info"},
        "ui": {"theme": theme, "accent": "cyan"},
    }


def write_config_atomic(path: Path, config: dict[str, Any]) -> None:
    """Atomically replace ``path`` with a private, fully serialized config."""

    path.parent.mkdir(parents=True, exist_ok=True)
    fd, raw_tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    tmp = Path(raw_tmp)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(_CONFIG_HEADER)
            yaml.safe_dump(config, handle, sort_keys=False, allow_unicode=True)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


_VALIDATION_WORKER_SELECTOR = "__jarn_internal_validation_worker__"
_VALIDATION_WORKER_CODE = (
    "from jarn.onboarding.wizard import _validation_worker_main; "
    "raise SystemExit(_validation_worker_main())"
)
_VALIDATION_REQUEST_MAX_BYTES = 1024 * 1024
_VALIDATION_RESPONSE_MAX_BYTES = 16 * 1024


class ValidationWorkerError(RuntimeError):
    """The isolated model-validation worker failed safely."""


def _validation_worker_command() -> list[str]:
    """Return a source- or PyInstaller-compatible private worker command."""

    if getattr(sys, "frozen", False):
        return [sys.executable, _VALIDATION_WORKER_SELECTOR]
    return [sys.executable, "-c", _VALIDATION_WORKER_CODE]


def _validation_worker_main() -> int:
    """Read one validation request from stdin and emit one redacted response."""

    from jarn.config.secrets import redact_secrets

    credential: str | None = None
    response: dict[str, Any]
    try:
        payload = sys.stdin.buffer.read(_VALIDATION_REQUEST_MAX_BYTES + 1)
        if len(payload) > _VALIDATION_REQUEST_MAX_BYTES:
            raise ValueError("validation request is too large")
        request = json.loads(payload)
        if not isinstance(request, dict):
            raise ValueError("validation request must be an object")
        profile = request.get("profile")
        model = request.get("model")
        raw_config = request.get("config")
        raw_credential = request.get("credential")
        if not isinstance(profile, str) or not profile:
            raise ValueError("validation profile is missing")
        if not isinstance(model, str) or not model:
            raise ValueError("validation model is missing")
        if not isinstance(raw_config, dict):
            raise ValueError("validation config must be an object")
        if raw_credential is not None and not isinstance(raw_credential, str):
            raise ValueError("validation credential has an invalid type")
        credential = raw_credential

        # Provider libraries sometimes print request diagnostics directly. Keep
        # them out of the IPC response and parent logs; only our bounded JSON is
        # written after this context exits.
        with (
            open(os.devnull, "w", encoding="utf-8") as sink,
            contextlib.redirect_stdout(sink),
            contextlib.redirect_stderr(sink),
        ):
            from jarn.config.loader import _build_config
            from jarn.providers import ModelFactory

            cfg = _build_config(raw_config)
            provider = cfg.providers.get(profile)
            if provider is None:
                raise ValueError("selected validation provider is not configured")
            # The parent resolves the selected reference and sends its value
            # only through stdin. ModelFactory therefore never needs to read
            # a provider credential from argv or the worker environment.
            provider.api_key = credential
            chat = ModelFactory(cfg).build(model)
            result = chat.invoke("ping")
            content = getattr(result, "content", result)
            response_chars = len(str(content))
        response = {"ok": True, "response_chars": response_chars}
    except BaseException as exc:
        known = {credential} if credential else None
        message = redact_secrets(str(exc), known=known)
        response = {
            "ok": False,
            "error_type": type(exc).__name__[:120],
            "message": message[:1000],
        }
    sys.stdout.write(json.dumps(response, ensure_ascii=False, separators=(",", ":")))
    sys.stdout.flush()
    return 0


def _kill_validation_worker(process: subprocess.Popen[bytes]) -> None:
    """Kill the validation process group and synchronously reap its leader."""

    if process.poll() is None:
        if os.name == "posix":
            try:
                os.killpg(process.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
            except OSError:
                process.kill()
        else:  # pragma: no cover - native Windows is not a supported runtime
            process.kill()
    process.communicate()


def _validation_worker_env(secret_env_var: str | None) -> dict[str, str]:
    """Copy a bounded validation environment without credentials or tracing.

    First-run validation must never inherit an operator's LangSmith/LangChain
    tracing session: doing so can export the setup ping and can leave the worker
    waiting for a background trace flush after it has already produced a result.
    """

    env = os.environ.copy()
    for variable in PROVIDER_ENV_VARS.values():
        env.pop(variable, None)
    if secret_env_var:
        env.pop(secret_env_var, None)
    for variable in (
        "LANGSMITH_API_KEY",
        "LANGSMITH_ENDPOINT",
        "LANGSMITH_PROJECT",
        "LANGCHAIN_API_KEY",
        "LANGCHAIN_ENDPOINT",
        "LANGCHAIN_PROJECT",
        "OTEL_EXPORTER_OTLP_ENDPOINT",
        "OTEL_EXPORTER_OTLP_HEADERS",
    ):
        env.pop(variable, None)
    env["LANGSMITH_TRACING"] = "false"
    env["LANGCHAIN_TRACING_V2"] = "false"
    return env


def _run_validation_request(
    profile: str,
    model: str,
    config: dict[str, Any],
    *,
    timeout: float,
) -> int:
    """Construct and ping a model in a bounded, killable isolated process."""

    from jarn.config.secrets import redact_secrets, resolve

    if timeout <= 0:
        raise ValueError("validation timeout must be greater than zero")
    request_config = deepcopy(config)
    providers = request_config.get("providers")
    selected = providers.get(profile) if isinstance(providers, dict) else None
    reference = selected.get("api_key") if isinstance(selected, dict) else None
    if reference is not None and not isinstance(reference, str):
        raise ValidationWorkerError("selected provider credential reference is invalid")
    credential = resolve(reference) if isinstance(reference, str) and reference else None
    secret_env_var: str | None = None
    if isinstance(reference, str) and reference.startswith("${") and reference.endswith("}"):
        secret_env_var = reference[2:-1]
    if isinstance(selected, dict):
        selected["api_key"] = None

    request = json.dumps(
        {
            "profile": profile,
            "model": model,
            "config": request_config,
            "credential": credential,
        },
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    if len(request) > _VALIDATION_REQUEST_MAX_BYTES:
        raise ValidationWorkerError("model validation request is too large")
    process = subprocess.Popen(  # noqa: S603 - fixed interpreter/private selector
        _validation_worker_command(),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=_validation_worker_env(secret_env_var),
        start_new_session=os.name == "posix",
    )
    try:
        stdout, _stderr = process.communicate(input=request, timeout=timeout)
    except subprocess.TimeoutExpired as exc:
        _kill_validation_worker(process)
        raise TimeoutError(f"no response within {timeout:.0f}s") from exc
    except BaseException:
        _kill_validation_worker(process)
        raise

    if process.returncode != 0:
        raise ValidationWorkerError(
            f"model validation worker exited with status {process.returncode}"
        )
    if len(stdout) > _VALIDATION_RESPONSE_MAX_BYTES:
        raise ValidationWorkerError("model validation worker returned an oversized response")
    try:
        response = json.loads(stdout)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValidationWorkerError("model validation worker returned an invalid response") from exc
    if not isinstance(response, dict):
        raise ValidationWorkerError("model validation worker returned an invalid response")
    if not response.get("ok"):
        raw_error_type = str(response.get("error_type") or "validation error")[:120]
        error_type = (
            "".join(char for char in raw_error_type if char.isalnum() or char in "._- ").strip()
            or "validation error"
        )
        message = redact_secrets(
            str(response.get("message") or "model validation failed"),
            known={credential} if credential else None,
        )[:1000]
        message = "".join(char for char in message if ord(char) >= 32).strip()
        raise ValidationWorkerError(f"{error_type}: {message}")
    response_chars = response.get("response_chars")
    if not isinstance(response_chars, int) or isinstance(response_chars, bool):
        raise ValidationWorkerError("model validation worker returned an invalid result")
    if response_chars < 0:
        raise ValidationWorkerError("model validation worker returned an invalid result")
    return response_chars


def _direct_ping_worker(chat: Any, sender: Any) -> None:
    """Compatibility worker for callers that already constructed a test model."""

    try:
        os.setsid()
    except OSError as exc:
        # The parent must never assume that a process group exists before this
        # handshake.  In particular, a contended runner can reach its timeout
        # before the forked child gets its first timeslice; blindly calling
        # killpg(child_pid) then races with setsid() and can leave the model
        # invocation alive after the timeout was reported.
        with contextlib.suppress(BaseException):
            sender.send(("init_error", type(exc).__name__, str(exc)))
        sender.close()
        return
    try:
        sender.send(("ready",))
        sender.send(("ok", chat.invoke("ping")))
    except BaseException as exc:
        try:
            sender.send(("error", exc))
        except BaseException:
            sender.send(("error_text", type(exc).__name__, str(exc)))
    finally:
        sender.close()


def _ping_with_timeout(chat: Any, timeout: float) -> Any:
    """Invoke an already-built test model in a killable and reaped process.

    Production validation uses :func:`_run_validation_request` so the model is
    constructed inside the source/frozen-compatible worker. This compatibility
    seam retains the historical private helper without leaving a daemon thread.
    """

    if timeout <= 0:
        raise ValueError("validation timeout must be greater than zero")
    if os.name != "posix":  # pragma: no cover - native Windows is unsupported
        raise RuntimeError("isolated validation requires a POSIX runtime")
    import multiprocessing

    context = multiprocessing.get_context("fork")
    receiver, sender = context.Pipe(duplex=False)
    process = context.Process(target=_direct_ping_worker, args=(chat, sender))
    process.start()
    worker_pid = process.pid
    if worker_pid is None:  # pragma: no cover - start either assigns it or raises
        process.close()
        raise RuntimeError("validation worker did not start")
    sender.close()
    deadline = time.monotonic() + timeout
    process_group_ready = False

    def _remaining() -> float:
        return max(0.0, deadline - time.monotonic())

    def _kill_and_reap() -> None:
        if process.is_alive():
            if process_group_ready:
                try:
                    os.killpg(worker_pid, signal.SIGKILL)
                except ProcessLookupError:
                    # The leader may have exited between is_alive() and killpg;
                    # Process.kill below remains a safe direct-child fallback.
                    with contextlib.suppress(ProcessLookupError):
                        process.kill()
            else:
                # The worker sends ``ready`` before invoking the model, so a
                # pre-handshake timeout cannot yet have spawned descendants.
                with contextlib.suppress(ProcessLookupError):
                    process.kill()
        process.join()

    try:
        if not receiver.poll(_remaining()):
            _kill_and_reap()
            raise TimeoutError(f"no response within {timeout:.0f}s")
        handshake = receiver.recv()
        if not isinstance(handshake, tuple) or not handshake:
            _kill_and_reap()
            raise RuntimeError("validation worker returned an invalid handshake")
        if handshake[0] == "init_error":
            _kill_and_reap()
            raise RuntimeError(f"{handshake[1]}: {handshake[2]}")
        if handshake[0] != "ready":
            _kill_and_reap()
            raise RuntimeError("validation worker did not establish isolation")
        process_group_ready = True

        if not receiver.poll(_remaining()):
            _kill_and_reap()
            raise TimeoutError(f"no response within {timeout:.0f}s")
        payload = receiver.recv()
        # Receiving the result does not excuse a lingering model/helper tree.
        # Give normal process teardown only the caller's remaining deadline,
        # then synchronously kill and reap the isolated group if necessary.
        process.join(timeout=_remaining())
        if process.is_alive():
            _kill_and_reap()
    finally:
        receiver.close()
        if process.is_alive():
            _kill_and_reap()
        process.close()
    if payload[0] == "ok":
        return payload[1]
    if payload[0] == "error":
        raise payload[1]
    raise RuntimeError(f"{payload[1]}: {payload[2]}")


def validate_config(
    profile: str, model: str, config: dict[str, Any], *, timeout: float = 120.0
) -> bool:
    """Send a 1-token ping to confirm the key/model work. Returns success.

    Shows a spinner while waiting — a local or remote model can need to cold-load,
    which may take ~1 min — and gives up after ``timeout`` so a stuck endpoint
    can't hang setup. Ctrl+C skips the wait."""
    from jarn.config.secrets import redact_secrets

    try:
        with console.status(layout.accent(_t("onboarding.validate.status"))):
            response_chars = _run_validation_request(
                profile,
                model,
                config,
                timeout=timeout,
            )
        console.print(
            f"  {layout.ok(grammar.GLYPH_OK)} {_t('onboarding.validate.ok', n=response_chars)}"
        )
        return True
    except KeyboardInterrupt:
        console.print("  " + layout.muted(_t("onboarding.validate.skipped")))
        return False
    except TimeoutError:
        console.print(
            f"  {layout.warn(grammar.GLYPH_WARN)} "
            f"{_t('onboarding.validate.timeout', seconds=f'{timeout:.0f}')}"
        )
        console.print("  " + layout.muted(_t("onboarding.validate.adjust")))
        return False
    except Exception as exc:  # noqa: BLE001
        provider_raw = config.get("providers", {}).get(profile, {})
        raw_key = provider_raw.get("api_key") if isinstance(provider_raw, dict) else None
        known = {raw_key} if isinstance(raw_key, str) and raw_key else None
        console.print(
            f"  {layout.warn(grammar.GLYPH_WARN)} "
            f"{_t('onboarding.validate.failed', error=redact_secrets(str(exc), known=known))}"
        )
        console.print("  " + layout.muted(_t("onboarding.validate.fix_later")))
        return False
