"""Interactive first-run wizard.

Runs in the plain terminal (before the TUI launches) using Rich prompts. Asks
for the default provider, how to store its API key (env var reference or the OS
keychain — never inlined), the default model, and theme; then writes
``~/.jarn/config.yaml`` and optionally validates the key with a tiny call.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import yaml
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

from jarn.config import paths
from jarn.config.defaults import (
    ALL_PROVIDERS,
    CLOUD_PROVIDERS,
    CUSTOM_OPENAI_PROFILE,
    DEFAULT_MODELS,
    EDITABLE_BASE_URL_PROFILES,
    PROVIDER_BASE_URLS,
    PROVIDER_ENV_VARS,
)
from jarn.config.secrets import file_fallback_notice, store_secret
from jarn.onboarding.providers import provider_hint
from jarn.providers import strip_profile
from jarn.tui.logo import TAGLINE, WORDMARK

console = Console()

_CLOUD = CLOUD_PROVIDERS
_PROFILES = ALL_PROVIDERS


def _detect_env_key() -> tuple[str, str] | None:
    """Probe known provider env vars and return (provider, env_var) for the first hit.

    Checks providers in priority order: anthropic, openai, openrouter, then the rest.
    Returns ``None`` when no key is found in the environment.
    """
    priority = ["anthropic", "openai", "openrouter"]
    rest = [p for p in ALL_PROVIDERS if p not in priority]
    for provider in priority + rest:
        env_var = PROVIDER_ENV_VARS.get(provider)
        if env_var and os.environ.get(env_var):
            return provider, env_var
    return None


def _recommended_provider(env_hit: tuple[str, str] | None) -> str:
    """Return the provider that should be marked '★ recommended'.

    Priority: env-key provider > anthropic (if ANTHROPIC_API_KEY set) > openrouter.
    """
    if env_hit is not None:
        return env_hit[0]
    if os.environ.get("ANTHROPIC_API_KEY"):
        return "anthropic"
    return "openrouter"


_CONFIG_HEADER = """\
# J.A.R.N. configuration — generated by `jarn setup`.
# API keys are referenced, never inlined:
#   ${ENV_VAR}                -> read from the environment
#   keychain:jarn/<provider>  -> read from the OS keychain
#   file:jarn/<provider>      -> read from ~/.jarn/secrets/ (keychain fallback)
# Docs: https://github.com/chayapats/jarn/tree/main/docs
"""


def profile_needs_base_url(profile: str) -> bool:
    """True when setup should collect a custom ``base_url`` for ``profile``."""
    return profile in EDITABLE_BASE_URL_PROFILES


def normalize_openai_base_url(url: str) -> str:
    """Normalize an OpenAI-compatible endpoint URL (append ``/v1`` when bare)."""
    cleaned = url.strip().rstrip("/")
    if not cleaned:
        raise ValueError("base URL is required")
    parsed = urlparse(cleaned)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise ValueError(f"invalid base URL {url!r} (expected http(s)://host[:port][/v1])")
    if parsed.path in ("", "/"):
        return f"{cleaned}/v1"
    return cleaned


def normalize_base_url(profile: str, url: str) -> str:
    """Normalize a provider base URL (Ollama keeps host-only; others get ``/v1``)."""
    cleaned = url.strip().rstrip("/")
    if not cleaned:
        raise ValueError("base URL is required")
    parsed = urlparse(cleaned)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise ValueError(f"invalid base URL {url!r}")
    if profile == "ollama":
        return cleaned
    return normalize_openai_base_url(url)


def derive_routing_models(profile: str, main_model: str) -> dict[str, Any]:
    """Build routing entries aligned with the user's chosen main model.

    Custom / placeholder defaults keep subagent and summarizer on the same model
    so ``/compact`` and delegated tasks don't point at ``your-model``.
    """
    defaults = DEFAULT_MODELS.get(profile, DEFAULT_MODELS["openrouter"])
    sub = defaults["subagent"]
    summ = defaults["summarizer"]
    sub_id = strip_profile(sub, profile)
    if profile == CUSTOM_OPENAI_PROFILE or sub_id in ("your-model", ""):
        sub = summ = main_model
    return {
        "main": main_model,
        "subagent": sub,
        "summarizer": summ,
        "fallback": [],
    }


def confirm_overwrite(*, force: bool = False) -> bool:
    """Ask before replacing an existing global config. Returns True to proceed."""
    config_path = paths.global_config_path()
    if force or not config_path.is_file():
        return True
    if Confirm.ask(f"{config_path} exists. Overwrite?", default=False):
        return True
    console.print("[yellow]Keeping existing config.[/yellow]")
    return False


def run_wizard(*, force: bool = False) -> Path | None:
    """Run the wizard and write the global config. Returns the config path."""
    if not confirm_overwrite(force=force):
        return paths.global_config_path()

    config_path = paths.global_config_path()
    paths.global_home().mkdir(parents=True, exist_ok=True)

    console.print(Panel.fit(f"[b cyan]{WORDMARK}[/b cyan]\n[dim]{TAGLINE}[/dim]",
                            border_style="cyan"))
    console.print("Let's get you set up. This writes [b]~/.jarn/config.yaml[/b].\n")

    # -- env detection: offer to use an existing key up-front --
    env_hit = _detect_env_key()
    recommended = _recommended_provider(env_hit)
    default_profile = recommended
    use_env = False

    if env_hit is not None:
        env_provider, env_var = env_hit
        console.print(
            f"[green]✓[/green] Found [b]{env_var}[/b] in your environment"
            f" — use it? [Y/n]",
        )
        use_env = Confirm.ask("", default=True)
        if use_env:
            default_profile = env_provider

    # Build the provider list with hints and recommendation tag
    provider_choices_display: list[str] = []
    for p in _PROFILES:
        hint = provider_hint(p)
        tag = " [yellow]★ recommended[/yellow]" if p == recommended else ""
        extra = (
            "  aggregator; needs a free openrouter.ai account"
            if p == "openrouter" and recommended == "openrouter" and env_hit is None
            else ""
        )
        provider_choices_display.append(f"  {p}  ({hint}){tag}{extra}")

    console.print("Available providers:")
    for line in provider_choices_display:
        console.print(line)
    console.print()

    profile = Prompt.ask(
        "Default provider profile", choices=list(_PROFILES), default=default_profile
    )

    # Pass env_hit only when the user ACCEPTED it earlier AND the chosen profile
    # matches the detected env provider — a decline must not silently reuse the key.
    key_env_hit = env_hit if (use_env and env_hit is not None and profile == env_hit[0]) else None
    api_key_ref = _configure_key(profile, env_hit=key_env_hit)
    base_url = _configure_base_url(profile) if profile_needs_base_url(profile) else None
    default_model = _prompt_model(profile)
    theme = Prompt.ask(
        "Theme", choices=["dark", "light", "high-contrast"], default="dark"
    )

    config = _build_config_dict(
        profile, api_key_ref, default_model, theme, base_url_override=base_url
    )
    config_path.write_text(_CONFIG_HEADER + yaml.safe_dump(config, sort_keys=False,
                                                           allow_unicode=True),
                           encoding="utf-8")
    console.print(f"\n[green]✔[/green] Wrote {config_path}")

    if profile in _CLOUD and Confirm.ask(
        "Validate the API key now? (a local model may need to load — can be slow)",
        default=True,
    ):
        validate_config(profile, default_model, config)

    console.print("\n[b cyan]All set.[/b cyan] Launch with [b]jarn[/b].")
    return config_path


def _prompt_model(profile: str) -> str:
    from jarn.providers import qualify_model_ref

    default_full = DEFAULT_MODELS[profile]["main"]
    default_id = strip_profile(default_full, profile)
    if profile == CUSTOM_OPENAI_PROFILE and default_id == "your-model":
        default_id = "gpt-4o"
    if profile_needs_base_url(profile) or "/" not in default_full:
        raw = Prompt.ask(
            "Model id on your endpoint" if profile == CUSTOM_OPENAI_PROFILE
            else f"Model id for {profile}",
            default=default_id,
        )
        return qualify_model_ref(raw, profile)
    return Prompt.ask("Default model (main agent)", default=default_full)


def _configure_key(
    profile: str,
    *,
    env_hit: tuple[str, str] | None = None,
) -> str | None:
    """Determine the API key reference for *profile*.

    When *env_hit* is provided and matches *profile* (i.e. the user confirmed
    using the detected env key), return the ``${ENV_VAR}`` reference immediately
    without prompting — keeping the key out of the config verbatim.
    """
    if profile not in _CLOUD:
        console.print(f"[dim]{profile} is local — no API key needed.[/dim]")
        return None

    env_var = PROVIDER_ENV_VARS.get(profile, f"{profile.upper()}_API_KEY")

    # If the detected env key belongs to this provider, use it as a reference.
    if env_hit is not None and env_hit[0] == profile:
        console.print(
            f"  [dim]J.A.R.N. will read the key from ${{{env_var}}}.[/dim]"
        )
        return f"${{{env_var}}}"

    console.print(f"\nHow should J.A.R.N. read your [b]{profile}[/b] API key?")
    method = Prompt.ask(
        "  storage", choices=["env", "keychain"], default="env"
    )
    if method == "env":
        console.print(f"  [dim]J.A.R.N. will read it from ${env_var}.[/dim]")
        return f"${{{env_var}}}"

    key = Prompt.ask("  paste API key", password=True)
    if key:
        stored = store_secret("jarn", profile, key)
        notice = file_fallback_notice(stored, provider=profile, env_var=env_var)
        if notice:
            console.print(f"[yellow]{notice}[/yellow]")
        else:
            console.print(f"  [green]✔[/green] stored in OS keychain (jarn/{profile})")
        return stored.reference
    return f"${{{env_var}}}"


def _configure_base_url(profile: str) -> str:
    default = PROVIDER_BASE_URLS.get(profile, "http://localhost:8000/v1")
    while True:
        raw = Prompt.ask(
            f"API base URL for {profile}",
            default=default,
        )
        try:
            return normalize_base_url(profile, raw)
        except ValueError as exc:
            console.print(f"  [yellow]![/yellow] {exc}")


def _build_config_dict(
    profile: str,
    api_key_ref: str | None,
    default_model: str,
    theme: str,
    *,
    mode: str = "ask",
    base_url_override: str | None = None,
) -> dict[str, Any]:
    providers: dict[str, Any] = {}
    for name in _PROFILES:
        entry: dict[str, Any] = {"type": name}
        if name in _CLOUD:
            entry["api_key"] = (
                api_key_ref if name == profile
                else f"${{{PROVIDER_ENV_VARS.get(name, name.upper() + '_API_KEY')}}}"
            )
        if name in PROVIDER_BASE_URLS:
            if name == profile and base_url_override:
                entry["base_url"] = base_url_override
            else:
                entry["base_url"] = PROVIDER_BASE_URLS[name]
        providers[name] = entry

    return {
        "default_profile": profile,
        "default_model": default_model,
        "permission_mode": mode,
        "providers": providers,
        "routing": derive_routing_models(profile, default_model),
        "budget": {"per_session_usd": 5.0, "hard_stop": True, "warn_at_pct": 80},
        "context": {"auto_compact": True, "compact_at_pct": 85},
        "execution": {"local_sandbox": "auto"},
        "permissions": {"allow": [], "deny": []},
        "observability": {"langsmith": False, "telemetry": False, "log_level": "info"},
        "ui": {"theme": theme, "accent": "cyan"},
    }


def _ping_with_timeout(chat: Any, timeout: float) -> Any:
    """Run a blocking ``chat.invoke('ping')`` but stop waiting after ``timeout``.

    Uses a daemon thread so a slow/cold model (or a black-holed endpoint) can't
    hang setup forever and never blocks process exit — the request finishes (or
    dies) in the background. Raises ``TimeoutError`` if no response in time."""
    import threading

    box: dict[str, Any] = {}

    def _run() -> None:
        try:
            box["resp"] = chat.invoke("ping")
        except Exception as exc:  # noqa: BLE001
            box["err"] = exc

    t = threading.Thread(target=_run, daemon=True)
    t.start()
    t.join(timeout)
    if t.is_alive():
        raise TimeoutError(f"no response within {timeout:.0f}s")
    if "err" in box:
        raise box["err"]
    return box["resp"]


def validate_config(
    profile: str, model: str, config: dict[str, Any], *, timeout: float = 120.0
) -> bool:
    """Send a 1-token ping to confirm the key/model work. Returns success.

    Shows a spinner while waiting — a local or remote model can need to cold-load,
    which may take ~1 min — and gives up after ``timeout`` so a stuck endpoint
    can't hang setup. Ctrl+C skips the wait."""
    from jarn.config.loader import _build_config
    from jarn.providers import ModelFactory

    try:
        cfg = _build_config(config)
        factory = ModelFactory(cfg)
        chat = factory.build(model)
        with console.status(
            "[cyan]validating[/cyan] — the model may need to load first "
            "(can take ~1 min); Ctrl+C to skip"
        ):
            resp = _ping_with_timeout(chat, timeout)
        console.print(f"  [green]✔[/green] model responded ({len(str(resp.content))} chars)")
        return True
    except KeyboardInterrupt:
        console.print(
            "  [dim]skipped — the model is still loading in the background; "
            "it'll work once warm.[/dim]"
        )
        return False
    except TimeoutError:
        console.print(
            f"  [yellow]![/yellow] validation timed out after {timeout:.0f}s — the "
            "model may still be loading; it should work once it's warm."
        )
        console.print("  [dim]Adjust the key/model later in ~/.jarn/config.yaml if needed.[/dim]")
        return False
    except Exception as exc:  # noqa: BLE001
        console.print(f"  [yellow]![/yellow] validation failed: {exc}")
        console.print("  [dim]You can fix the key/model later in ~/.jarn/config.yaml.[/dim]")
        return False
