"""Provider & model-routing subsystem."""

from jarn.providers.models import (
    DEMO_PROFILE,
    ModelFactory,
    ModelRef,
    ModelResolutionError,
    RemoteModelCatalog,
    RemoteModelDiscoveryError,
    RemoteModelRecord,
    build_demo_model,
    demo_provider_config,
    fetch_remote_model_catalog,
    is_demo_active,
    list_remote_models,
    parse_model_ref,
    qualify_model_ref,
    remote_catalog_account_fingerprint,
    remote_context_window,
    strip_profile,
    suggest_slug,
    supports_remote_model_catalog,
)

__all__ = [
    "DEMO_PROFILE",
    "ModelFactory",
    "ModelRef",
    "ModelResolutionError",
    "RemoteModelCatalog",
    "RemoteModelDiscoveryError",
    "RemoteModelRecord",
    "build_demo_model",
    "demo_provider_config",
    "fetch_remote_model_catalog",
    "is_demo_active",
    "list_remote_models",
    "parse_model_ref",
    "qualify_model_ref",
    "remote_context_window",
    "remote_catalog_account_fingerprint",
    "strip_profile",
    "supports_remote_model_catalog",
    "suggest_slug",
]
